// Generated using https://anseki.github.io/gnirts/

//prettier-ignore
const secret1 = (function(){var m=Array.prototype.slice.call(arguments),g=m.shift();return m.reverse().map(function(r,Q){return String.fromCharCode(r-g-2-Q)}).join('')})(30,67,150,144,142)+(812282).toString(36).toLowerCase()+(628).toString(36).toLowerCase().split('').map(function(a){return String.fromCharCode(a.charCodeAt()+(-71))}).join('')+(function(){var K=Array.prototype.slice.call(arguments),b=K.shift();return K.reverse().map(function(Q,w){return String.fromCharCode(Q-b-56-w)}).join('')})(43,220)+(894).toString(36).toLowerCase()+(23).toString(36).toLowerCase().split('').map(function(H){return String.fromCharCode(H.charCodeAt()+(-71))}).join('')+(1130).toString(36).toLowerCase()+(16).toString(36).toLowerCase().split('').map(function(U){return String.fromCharCode(U.charCodeAt()+(-71))}).join('')+(778442).toString(36).toLowerCase()+(16).toString(36).toLowerCase().split('').map(function(I){return String.fromCharCode(I.charCodeAt()+(-71))}).join('')+(1068).toString(36).toLowerCase()+(function(){var x=Array.prototype.slice.call(arguments),S=x.shift();return x.reverse().map(function(m,a){return String.fromCharCode(m-S-54-a)}).join('')})(39,193,197,126,204)+(27).toString(36).toLowerCase()+(16).toString(36).toLowerCase().split('').map(function(c){return String.fromCharCode(c.charCodeAt()+(-71))}).join('')+(function(){var z=Array.prototype.slice.call(arguments),G=z.shift();return z.reverse().map(function(y,c){return String.fromCharCode(y-G-25-c)}).join('')})(13,138)+(24).toString(36).toLowerCase()+(function(){var L=Array.prototype.slice.call(arguments),o=L.shift();return L.reverse().map(function(m,g){return String.fromCharCode(m-o-60-g)}).join('')})(62,233,241)

//prettier-ignore
const secret2 = (671).toString(36).toLowerCase()+(16).toString(36).toLowerCase().split('').map(function(p){return String.fromCharCode(p.charCodeAt()+(-71))}).join('')+(1061).toString(36).toLowerCase()+(function(){var X=Array.prototype.slice.call(arguments),V=X.shift();return X.reverse().map(function(M,A){return String.fromCharCode(M-V-6-A)}).join('')})(39,165,165,153,159,78,146)+(16).toString(36).toLowerCase().split('').map(function(J){return String.fromCharCode(J.charCodeAt()+(-71))}).join('')+(879).toString(36).toLowerCase()+(16).toString(36).toLowerCase().split('').map(function(B){return String.fromCharCode(B.charCodeAt()+(-71))}).join('')+(492).toString(36).toLowerCase()+(function(){var I=Array.prototype.slice.call(arguments),S=I.shift();return I.reverse().map(function(D,V){return String.fromCharCode(D-S-2-V)}).join('')})(34,165,151,167,159,146,161,150,144,75,159,152,161,71,82,146,147)+(16).toString(36).toLowerCase().split('').map(function(e){return String.fromCharCode(e.charCodeAt()+(-71))}).join('')+(38210).toString(36).toLowerCase()+(16).toString(36).toLowerCase().split('').map(function(x){return String.fromCharCode(x.charCodeAt()+(-71))}).join('')+(1717162949).toString(36).toLowerCase()+(10).toString(36).toLowerCase().split('').map(function(O){return String.fromCharCode(O.charCodeAt()+(-39))}).join('')+(599).toString(36).toLowerCase().split('').map(function(g){return String.fromCharCode(g.charCodeAt()+(-71))}).join('')+(function(){var y=Array.prototype.slice.call(arguments),S=y.shift();return y.reverse().map(function(s,E){return String.fromCharCode(s-S-9-E)}).join('')})(23,130,140)+(1238).toString(36).toLowerCase()+(function(){var o=Array.prototype.slice.call(arguments),n=o.shift();return o.reverse().map(function(R,r){return String.fromCharCode(R-n-38-r)}).join('')})(52,131,206,204)

//prettier-ignore
const secret3 = (38210).toString(36).toLowerCase()+(16).toString(36).toLowerCase().split('').map(function(j){return String.fromCharCode(j.charCodeAt()+(-71))}).join('')+(1354829038).toString(36).toLowerCase()+(16).toString(36).toLowerCase().split('').map(function(K){return String.fromCharCode(K.charCodeAt()+(-71))}).join('')+(676).toString(36).toLowerCase()+(16).toString(36).toLowerCase().split('').map(function(q){return String.fromCharCode(q.charCodeAt()+(-71))}).join('')+(762022611).toString(36).toLowerCase()+(16).toString(36).toLowerCase().split('').map(function(u){return String.fromCharCode(u.charCodeAt()+(-71))}).join('')+(23).toString(36).toLowerCase()+(function(){var G=Array.prototype.slice.call(arguments),x=G.shift();return G.reverse().map(function(u,y){return String.fromCharCode(u-x-2-y)}).join('')})(3,135,130,48,131,125,123,44,127,127,107,40,51,125,116)+(18).toString(36).toLowerCase()+(function(){var r=Array.prototype.slice.call(arguments),j=r.shift();return r.reverse().map(function(i,a){return String.fromCharCode(i-j-21-a)}).join('')})(31,159,171,157,159,86,154,168)

//prettier-ignore
const secret4 = (677).toString(36).toLowerCase()+(23).toString(36).toLowerCase().split('').map(function(D){return String.fromCharCode(D.charCodeAt()+(-71))}).join('')+(28).toString(36).toLowerCase()+(16).toString(36).toLowerCase().split('').map(function(Z){return String.fromCharCode(Z.charCodeAt()+(-71))}).join('')+(30701).toString(36).toLowerCase()+(16).toString(36).toLowerCase().split('').map(function(v){return String.fromCharCode(v.charCodeAt()+(-71))}).join('')+(812282).toString(36).toLowerCase()+(1024).toString(36).toLowerCase().split('').map(function(E){return String.fromCharCode(E.charCodeAt()+(-71))}).join('')+(389).toString(36).toLowerCase()+(16).toString(36).toLowerCase().split('').map(function(Y){return String.fromCharCode(Y.charCodeAt()+(-71))}).join('')+(38210).toString(36).toLowerCase()+(function(){var t=Array.prototype.slice.call(arguments),F=t.shift();return t.reverse().map(function(n,Y){return String.fromCharCode(n-F-15-Y)}).join('')})(34,179,176,178,162,91,165,168,167,163,86,99,164,162,166,81)+(22563).toString(36).toLowerCase()+(16).toString(36).toLowerCase().split('').map(function(r){return String.fromCharCode(r.charCodeAt()+(-71))}).join('')+(492).toString(36).toLowerCase()+(function(){var R=Array.prototype.slice.call(arguments),S=R.shift();return R.reverse().map(function(F,r){return String.fromCharCode(F-S-0-r)}).join('')})(21,130,62,130,132,143,58,135,129,55,132,140)+(13737).toString(36).toLowerCase()+(16).toString(36).toLowerCase().split('').map(function(j){return String.fromCharCode(j.charCodeAt()+(-71))}).join('')+(function(){var j=Array.prototype.slice.call(arguments),h=j.shift();return j.reverse().map(function(H,x){return String.fromCharCode(H-h-48-x)}).join('')})(46,145,205,196,193,211,209)

export function getSecret(index) {
  return [secret1, secret2, secret3, secret4][index];
}
